config/routes.rb
Rails.application.routes.draw do
  resources :remuneracoes
  resources :turnos
  resources :funcionarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/remuneracao.rb
class Remuneracao < ApplicationRecord
  belongs_to :funcionario
end

app/models/turno.rb
class Turno < ApplicationRecord
  belongs_to :funcionario
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome)
    end
end

app/controllers/remuneracoes_controller.rb
class RemuneracoesController < ApplicationController
  before_action :set_remuneracao, only: [:show, :edit, :update, :destroy]

  # GET /remuneracoes
  # GET /remuneracoes.json
  def index
    @remuneracoes = Remuneracao.all
  end

  # GET /remuneracoes/1
  # GET /remuneracoes/1.json
  def show
  end

  # GET /remuneracoes/new
  def new
    @remuneracao = Remuneracao.new
  end

  # GET /remuneracoes/1/edit
  def edit
  end

  # POST /remuneracoes
  # POST /remuneracoes.json
  def create
    @remuneracao = Remuneracao.new(remuneracao_params)

    respond_to do |format|
      if @remuneracao.save
        format.html { redirect_to @remuneracao, notice: 'Remuneracao was successfully created.' }
        format.json { render :show, status: :created, location: @remuneracao }
      else
        format.html { render :new }
        format.json { render json: @remuneracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remuneracoes/1
  # PATCH/PUT /remuneracoes/1.json
  def update
    respond_to do |format|
      if @remuneracao.update(remuneracao_params)
        format.html { redirect_to @remuneracao, notice: 'Remuneracao was successfully updated.' }
        format.json { render :show, status: :ok, location: @remuneracao }
      else
        format.html { render :edit }
        format.json { render json: @remuneracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remuneracoes/1
  # DELETE /remuneracoes/1.json
  def destroy
    @remuneracao.destroy
    respond_to do |format|
      format.html { redirect_to remuneracoes_url, notice: 'Remuneracao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remuneracao
      @remuneracao = Remuneracao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def remuneracao_params
      params.require(:remuneracao).permit(:funcionario_id, :salario)
    end
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: [:show, :edit, :update, :destroy]

  # GET /turnos
  # GET /turnos.json
  def index
    @turnos = Turno.all
  end

  # GET /turnos/1
  # GET /turnos/1.json
  def show
  end

  # GET /turnos/new
  def new
    @turno = Turno.new
  end

  # GET /turnos/1/edit
  def edit
  end

  # POST /turnos
  # POST /turnos.json
  def create
    @turno = Turno.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno was successfully created.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnos/1
  # PATCH/PUT /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to @turno, notice: 'Turno was successfully updated.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1
  # DELETE /turnos/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turno_params
      params.require(:turno).permit(:funcionario_id, :entrada, :saida)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/remuneracoes_helper.rb
module RemuneracoesHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= link_to 'Show', funcionario %></td>
        <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestaoDePonto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/remuneracoes/_form.html.erb
<%= form_with(model: remuneracao) do |form| %>
  <% if remuneracao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remuneracao.errors.count, "error") %> prohibited this remuneracao from being saved:</h2>

      <ul>
        <% remuneracao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.text_field :funcionario_id %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.text_field :salario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/remuneracoes/edit.html.erb
<h1>Editing Remuneracao</h1>

<%= render 'form', remuneracao: @remuneracao %>

<%= link_to 'Show', @remuneracao %> |
<%= link_to 'Back', remuneracoes_path %>

app/views/remuneracoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Remuneracoes</h1>

<table>
  <thead>
    <tr>
      <th>Funcionario</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @remuneracoes.each do |remuneracao| %>
      <tr>
        <td><%= remuneracao.funcionario_id %></td>
        <td><%= remuneracao.salario %></td>
        <td><%= link_to 'Show', remuneracao %></td>
        <td><%= link_to 'Edit', edit_remuneracao_path(remuneracao) %></td>
        <td><%= link_to 'Destroy', remuneracao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remuneracao', new_remuneracao_path %>

app/views/remuneracoes/new.html.erb
<h1>New Remuneracao</h1>

<%= render 'form', remuneracao: @remuneracao %>

<%= link_to 'Back', remuneracoes_path %>

app/views/remuneracoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Funcionario:</strong>
  <%= @remuneracao.funcionario_id %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @remuneracao.salario %>
</p>

<%= link_to 'Edit', edit_remuneracao_path(@remuneracao) %> |
<%= link_to 'Back', remuneracoes_path %>

app/views/turnos/_form.html.erb
<%= form_with(model: turno) do |form| %>
  <% if turno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turno.errors.count, "error") %> prohibited this turno from being saved:</h2>

      <ul>
        <% turno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.text_field :funcionario_id %>
  </div>

  <div class="field">
    <%= form.label :entrada %>
    <%= form.datetime_select :entrada %>
  </div>

  <div class="field">
    <%= form.label :saida %>
    <%= form.datetime_select :saida %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turnos/edit.html.erb
<h1>Editing Turno</h1>

<%= render 'form', turno: @turno %>

<%= link_to 'Show', @turno %> |
<%= link_to 'Back', turnos_path %>

app/views/turnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turnos</h1>

<table>
  <thead>
    <tr>
      <th>Funcionario</th>
      <th>Entrada</th>
      <th>Saida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnos.each do |turno| %>
      <tr>
        <td><%= turno.funcionario_id %></td>
        <td><%= turno.entrada %></td>
        <td><%= turno.saida %></td>
        <td><%= link_to 'Show', turno %></td>
        <td><%= link_to 'Edit', edit_turno_path(turno) %></td>
        <td><%= link_to 'Destroy', turno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turno', new_turno_path %>

app/views/turnos/new.html.erb
<h1>New Turno</h1>

<%= render 'form', turno: @turno %>

<%= link_to 'Back', turnos_path %>

app/views/turnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Funcionario:</strong>
  <%= @turno.funcionario_id %>
</p>

<p>
  <strong>Entrada:</strong>
  <%= @turno.entrada %>
</p>

<p>
  <strong>Saida:</strong>
  <%= @turno.saida %>
</p>

<%= link_to 'Edit', edit_turno_path(@turno) %> |
<%= link_to 'Back', turnos_path %>